[build]
  command = "bundle exec jekyll build"
  publish = "_site"
  functions = "netlify/functions"

[build.environment]
  JEKYLL_ENV = "production"
  NODE_VERSION = "20"

# ✅ NETLIFY FUNCTIONS (Priyorite)
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ✅ NETLIFY CMS ADMIN
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# ❌ 404 TOUJOURS AN DERNIER
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
